name: Release

on:
  release:
    types: [created]

jobs:
  release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: polybar-reddit
            asset_name: polybar-reddit
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable         
      - name: Dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install libxcb-composite0-dev
      - name: Build project
        run: cargo build --release --locked
      - name: Rust Release binary
        uses: Douile/rust-build.action@v0.1.26
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUSTTARGET: ${{ matrix.target }}
          EXTRA_FILES: "README.md LICENSE"
